(eval-when (:compile-toplevel :load-toplevel :execute)
  (unless (find-package :eric)
    (ql:quickload "eric"))
  (unless (find-package :melisma)
    (load (compile-file "/home/eric/projects/melisma/melisma.lisp"))))

(defpackage #:piece
  (:use #:cl #:melisma))

(in-package #:piece)

(play-lilypond
 (render-lilypond "piano" "c \\major" 240
		  (make-note :duration 4 :pitch 12)
		  (make-note :duration 4 :pitch 14)
		  (make-note :duration 4 :pitch 14)
		  (make-note :duration 4 :pitch 12)
		  (make-note :voice :b :duration 1)
		  (make-note :duration 4 :pitch 12)
		  (make-note :duration 2)
		  (make-note :duration 4 :pitch 12)
		  (make-note :voice :b :duration 1)
		  (make-note :duration 4 :pitch 15)
		  (make-note :duration 4 :pitch 15)
		  (make-note :duration 4 :pitch 12)
		  (make-note :duration 4 :pitch 12)
		  (make-note :voice :b :duration 1)
		  (make-note :duration 2)
		  (make-note :duration 4 :pitch 12)
		  (make-note :duration 4 :pitch 14)
		  (make-note :voice :b :duration 1)
		  (make-note :duration 4 :pitch 14)
		  (make-note :duration 4 :pitch 14)
		  (make-note :duration 4 :pitch 14)
		  (make-note :duration 4 :pitch 14)
		  (make-note :voice :b :duration 1)
		  (make-note :duration 4 :pitch 14)
		  (make-note :duration 4 :pitch 14)
		  (make-note :voice :b :duration 1 :pitch 0)
		  (make-note :duration 1 :pitch 12)
		  (make-note :voice :b :duration 1 :pitch 0)
		  ))
